# 自动化测试

name: test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the feature/component branch
  push:
    branches: 
      - feature/component
    paths:
      - '.github/workflows/**'
      - '__test__/**'
      - 'src/**'
  pull_request:
    branches: [ feature/component ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2 # git pull 获取当前最新代码
      - name: use Node.js
        uses: actions/setup-node@v2 # 安装nodejs | 第三方的actions
        with: 
          node-version: 14
      - name: print node version
        run: |
          node -v
          npm -v
          echo 'hello github'
  test2: 
    runs-on: ubuntu-latest
    steps: 
      - run: touch a.txt
      - run: echo 100 > a.txt
      - run: cat a.txt
      
